# Generated by Django 4.1.13 on 2025-10-16 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alianza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CargoSegen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('fecha_curso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.niveleducativo')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('gerencia_contexto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.gerencia')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilLaboral',
            fields=[
                ('cedula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='asistencia.persona')),
                ('alianza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.alianza')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.cargo')),
                ('cargo_segen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.cargosegen')),
                ('coordinacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.coordinacion')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.estado')),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.gerencia')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('otro_telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('hora_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado', models.BooleanField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.persona')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.curso')),
                ('encuentra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.ubicacion')),
            ],
            options={
                'unique_together': {('cedula', 'curso_id')},
            },
        ),
    ]
