# Generated by Django 4.1.13 on 2025-10-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_sexo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coordinacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gerencia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
